const imgSrcPath = './../Images/';
const images = {
/*
  drawer_antiquruby_logo: require(imgSrcPath + "drawer_logo.png"),
  activeCategory: require(imgSrcPath + "activeCategory.png"),
  activeGift: require(imgSrcPath + "activeGift.png"),
  activeHome: require(imgSrcPath + "activeHome.png"),
  dots: require(imgSrcPath + "activess.png"),
  addUserIcon: require(imgSrcPath + "addUserIcon.png"),
  artical_fab: require(imgSrcPath + "artical_fab.png"),
  backArrow: require(imgSrcPath + "backArrow.png"),
  backArrowSignUpTen: require(imgSrcPath + "backArrowGrey.png"),
  backBlackArrow: require(imgSrcPath + "backBlackArrow.png"),
  bathRoomBlue: require(imgSrcPath + "bathroom_blue.png"),
  bedRoomBlue: require(imgSrcPath + "bedroom_blue.png"),
  bell_fab: require(imgSrcPath + "bell_fab.png"),
  bellnoti: require(imgSrcPath + "bellnoti.png"),
  bgtwentyseven: require(imgSrcPath + "bgtwentyseven.png"),
  blueCameraIcon: require(imgSrcPath + "blueCameraIcon.png"),
  book: require(imgSrcPath + "book.png"),
  bookCaseBlue: require(imgSrcPath + "bookcase_blue.png"),
  BreadAndPastries: require(imgSrcPath + "BreadAndPastries.png"),
  bubbleIcon: require(imgSrcPath + "bubbleIcon.png"),
  cart_icon: require(imgSrcPath + "cart_icon.png"),
  cart: require(imgSrcPath + "cart.png"),
  chatIcon: require(imgSrcPath + "chatIcon.png"),
  chbox_selected_signin_seven: require(imgSrcPath + "chbox_selected_signin_seven.png"),
  chbox_selected: require(imgSrcPath + "chbox_selected_signin_six.png"),
  chBoxProductShare: require(imgSrcPath + "checkBoxProductShare.png"),
  close_signin_15: require(imgSrcPath + "close_signin_15.png"),
  cloude: require(imgSrcPath + "cloude.png"),
  */
  comments: require(imgSrcPath + "comments.png"),
    /*
  country: require(imgSrcPath + "country.png"),
  createMessage: require(imgSrcPath + "createMessage.png"),
  Dairy: require(imgSrcPath + "Dairy.png"),
  deleteIcon: require(imgSrcPath + "deleteIcon.png"),
  diningRoomBlue: require(imgSrcPath + "diningroom_blue.png"),
  downArrowIcon: require(imgSrcPath + "downArrowIcon.png"),
  draw: require(imgSrcPath + "draw.png"),
  drawerBG: require(imgSrcPath + "drawerBG.png"),
  eclipse: require(imgSrcPath + "eclipse.png"),
  emoji: require(imgSrcPath + "emoji.png"),
  facebook: require(imgSrcPath + "facebook.png"),
  facebookIcon: require(imgSrcPath + "facebookIcon.png"),
  fashion: require(imgSrcPath + "fashion.png"),
  favorite_fab: require(imgSrcPath + "favorite_fab.png"),
  FbIcon: require(imgSrcPath + "fbicon.png"),
  film: require(imgSrcPath + "film.png"),
  filterIcon: require(imgSrcPath + "filterIcon.png"),
  Fish: require(imgSrcPath + "Fish.png"),
  food: require(imgSrcPath + "food.png"),
  friends_fab: require(imgSrcPath + "friends_fab.png"),
  Fruit: require(imgSrcPath + "Fruit.png"),
  game: require(imgSrcPath + "game.png"),
  googlePlusIcon: require(imgSrcPath + "googlePlusIcon.png"),
  gradientTitleBarBG: require(imgSrcPath + "gradient_bg.png"),
  heartRedIcon: require(imgSrcPath + "heartRedIcon.png"),
  heavymetal: require(imgSrcPath + "heavymetal.png"),
  admob: require(imgSrcPath + "ic_ad_mob.png"),
  addUserGray: require(imgSrcPath + "ic_add_user_gray.png"),
  */
  ic_address: require(imgSrcPath + "ic_address.png"),
    /*
  albumIcon: require(imgSrcPath + "ic_album.png"),
  bathRoom: require(imgSrcPath + "ic_bathroom.png"),
  bedRoom: require(imgSrcPath + "ic_bedroom.png"),
  bookCase: require(imgSrcPath + "ic_bookcase.png"),
  cameraIcon: require(imgSrcPath + "ic_camera.png"),
  cartIconWhite: require(imgSrcPath + "ic_cart.png"),
  ic_check_box: require(imgSrcPath + "ic_check_box.png"),
  commentWhiteIcon: require(imgSrcPath + "ic_comment_white.png"),
  */
  ic_details: require(imgSrcPath + "ic_details.png"),
    /*
  diningRoom: require(imgSrcPath + "ic_dining_room.png"),
  discover: require(imgSrcPath + "ic_discover.png"),
  discoveryActiveIcon: require(imgSrcPath + "ic_discovery_active.png"),
  discoveryIcon: require(imgSrcPath + "ic_discovery.png"),
  favouriteActiveIcon: require(imgSrcPath + "ic_favourite_active.png"),
  favouriteIcon: require(imgSrcPath + "ic_favourite.png"),
  */
  ic_get_reward: require(imgSrcPath + "ic_get_reward.png"),
    /*
  googleWhite: require(imgSrcPath + "ic_google_white.png"),
  google: require(imgSrcPath + "ic_google.png"),
  heartWhiteIcon: require(imgSrcPath + "ic_heart_white.png"),
  backArrowSignUpNine: require(imgSrcPath + "ic_Left_arrow_black_su09.png"),
  libraryIcon: require(imgSrcPath + "ic_library.png"),
  livingRoom: require(imgSrcPath + "ic_living_room.png"),
  TWIcon: require(imgSrcPath + "ic_logo_twitter_signin_ten.png"),
  */
  ic_logout: require(imgSrcPath + "ic_logout_yellow.png"),
  /*
  logoutIcon: require(imgSrcPath + "ic_logout.png"),
  mapPinIcon: require(imgSrcPath + "ic_map_pin.png"),
  mapPinWhite: require(imgSrcPath + "ic_map_pin.png"),
  masterCard: require(imgSrcPath + "ic_master_card.png"),
  menuAlert: require(imgSrcPath + "ic_menu_alert.png"),
  menuIcon: require(imgSrcPath + "ic_menu_white.png"),
  messageActiveIcon: require(imgSrcPath + "ic_message_active.png"),
  messageIcon: require(imgSrcPath + "ic_message.png"),
  moreWhiteIcon: require(imgSrcPath + "ic_more_white.png"),
  musicIcon: require(imgSrcPath + "ic_music.png"),
  myLikesIcon: require(imgSrcPath + "ic_my_likes.png"),
  nearByIcon: require(imgSrcPath + "ic_nearby_inactive.png"),
  nearByActiveIcon: require(imgSrcPath + "ic_nearby.png"),
  newArrivalFour: require(imgSrcPath + "ic_new_arrivals_four.png"),
  newArrivalOne: require(imgSrcPath + "ic_new_arrivals_one.png"),
  newArrivalThree: require(imgSrcPath + "ic_new_arrivals_three.png"),
  newArrivalTwo: require(imgSrcPath + "ic_new_arrivals_two.png"),
  */
  ic_notification: require(imgSrcPath + "ic_notification.png"),
  ic_order: require(imgSrcPath + "ic_order.png"),
  /*
  payPal: require(imgSrcPath + "ic_paypal.png"),
  phone: require(imgSrcPath + "ic_phone.png"),
  profileActiveIcon: require(imgSrcPath + "ic_profile_active.png"),
  profileIcon: require(imgSrcPath + "ic_profile.png"),
  radioIcon: require(imgSrcPath + "ic_radio.png"),
  searchGreyIcon: require(imgSrcPath + "ic_search_grey.png"),
  settingBlack: require(imgSrcPath + "ic_setting_black.png"),
  setting: require(imgSrcPath + "ic_setting.png"),
  slideUpArrowIcon: require(imgSrcPath + "ic_slide_up_arrow.png"),
  tvStand: require(imgSrcPath + "ic_tv_stand.png"),
  ic_uncheck: require(imgSrcPath + "ic_uncheck.png"),
  userGroup: require(imgSrcPath + "ic_user.png"),
  video: require(imgSrcPath + "ic_video.png"),
  visaCard: require(imgSrcPath + "ic_visa.png"),
  inviteFriendsLogo: require(imgSrcPath + "inviteFriendsLogo.png"),
  leftChatIndicator: require(imgSrcPath + "leftChatIndicator.png"),
  likes: require(imgSrcPath + "likes.png"),
  livingRoomBlue: require(imgSrcPath + "livingroom_blue.png"),
  location: require(imgSrcPath + "location.png"),
  lockIcon: require(imgSrcPath + "lockIcon.png"),
  mail: require(imgSrcPath + "mail.png"),
  Meat: require(imgSrcPath + "Meat.png"),
  message_fab: require(imgSrcPath + "message_fab.png"),
  messageBlueIcon: require(imgSrcPath + "messageBlueIcon.png"),
  mnavigation: require(imgSrcPath + "mnavigation.png"),
  msignin: require(imgSrcPath + "msignin.png"),
  msignup: require(imgSrcPath + "msignup.png"),
  msocial: require(imgSrcPath + "msocial.png"),
  muser: require(imgSrcPath + "muser.png"),
  music: require(imgSrcPath + "music.png"),
  mwalkthrough: require(imgSrcPath + "mwalkthrough.png"),
  normalCategory: require(imgSrcPath + "normalCategory.png"),
  normalGift: require(imgSrcPath + "normalGift.png"),
  normalHome: require(imgSrcPath + "normalHome.png"),
  notificationProfileIcon: require(imgSrcPath + "notificationProfileIcon.png"),
  optionIcon: require(imgSrcPath + "optionIcon.png"),
  product_four: require(imgSrcPath + "product_four.png"),
  product_one: require(imgSrcPath + "product_one.png"),
  product_three: require(imgSrcPath + "product_three.png"),
  product_two: require(imgSrcPath + "product_two.png"),
  productDetailImageOne: require(imgSrcPath + "productDetailImageOne.png"),
  productOrderOne: require(imgSrcPath + "productOrderOne.png"),
  productOrderTwo: require(imgSrcPath + "productOrderTwo.png"),
  profileMenu: require(imgSrcPath + "profileMenu.png"),
  rightArrowGreen: require(imgSrcPath + "right_arrow_green.png"),
  rightChatIndicator: require(imgSrcPath + "rightChatIndicator.png"),
  roundedcross: require(imgSrcPath + "roundedcross.png"),
  search_fab: require(imgSrcPath + "search_fab.png"),
  search: require(imgSrcPath + "search.png"),
  searchIcon: require(imgSrcPath + "searchIcon.png"),
  settingsIcon: require(imgSrcPath + "settingIcon.png"),
  sliderColorImgOne: require(imgSrcPath + "sliderColorImgOne.png"),
  sliderColorImgThree: require(imgSrcPath + "sliderColorImgThree.png"),
  sliderColorImgTwo: require(imgSrcPath + "sliderColorImgTwo.png"),
  sliderIcon: require(imgSrcPath + "sliderIcon.png"),
  sortIcon: require(imgSrcPath + "sortIcon.png"),
  sport: require(imgSrcPath + "sport.png"),
  starEmpty1: require(imgSrcPath + "starEmpty1.png"),
  starFilled1: require(imgSrcPath + "starFilled1.png"),
  starHalf1: require(imgSrcPath + "starHalf1.png"),
  timer: require(imgSrcPath + "timer.png"),
  travel: require(imgSrcPath + "travel.png"),
  tvStandBlue: require(imgSrcPath + "tv_stands_blue.png"),
  twitterIcon: require(imgSrcPath + "twitterIcon.png"),
  upArrowIcon: require(imgSrcPath + "upArrowIcon.png"),
  Vagitable: require(imgSrcPath + "Vagitable.png"),
  videoIcon: require(imgSrcPath + "videoIcon.png"),
  voiceRecordingIcon: require(imgSrcPath + "voice.png"),
  watchIcon: require(imgSrcPath + "watch.png"),
  heartWhiteEmpty: require(imgSrcPath + "white_empty_heart.png"),
  whiteTriangleIcon: require(imgSrcPath + "whiteTriangleIcon.png"),
  wishListItemOne: require(imgSrcPath + "wishListItemOne.png"),
  wishListItemTwo: require(imgSrcPath + "wishListItemTwo.png"),
  flagIndonesia: require(imgSrcPath + "flagIndonesia.png"),
  flagMalasia: require(imgSrcPath + "flagMalasia.png"),
  flagPhilippines: require(imgSrcPath + "flagPhilippines.png"),
  flagSingapore: require(imgSrcPath + "flagSingapore.png"),
  flagThailand: require(imgSrcPath + "flagThailand.png"),
  flagVietNam: require(imgSrcPath + "flagVietNam.png"),
  brandAramani: require(imgSrcPath + "brand_armani.png"),
  brandAvenue: require(imgSrcPath + "brand_avenue.png"),
  brandBebe: require(imgSrcPath + "brand_bebe.png"),
  brandColvinJeans: require(imgSrcPath + "brand_colvin_jeans.png"),
  brandDockers: require(imgSrcPath + "brand_dockers.png"),
  brandEllamoss: require(imgSrcPath + "brand_ellamoss.png"),
  brandFossil: require(imgSrcPath + "brand_fossil.png"),
  brandHurley: require(imgSrcPath + "brand_hurley.png"),
  brandKarmaLoop: require(imgSrcPath + "brand_karma_loop.png"),
  brandLevis: require(imgSrcPath + "brand_levis.png"),
  brandMango: require(imgSrcPath + "brand_mango.png"),
  brandMankind: require(imgSrcPath + "brand_mankind.png"),
  brandMarciano: require(imgSrcPath + "brand_marciano.png"),
  brandMiraclesuite: require(imgSrcPath + "brand_miraclesuite.png"),
  brandWomanWithin: require(imgSrcPath + "brand_woman_within.png"),
  roundLike: require(imgSrcPath + "round_like.png"),
  roundShare: require(imgSrcPath + "round_share.png"),*/
  homeSwiperOne: require(imgSrcPath + "home_swiper_one.png"),
  homeSwiperTwo: require(imgSrcPath + "home_swiper_two.png"),
  homeSwiperThree: require(imgSrcPath + "home_swiper_three.png"),
  /*womenCategory: require(imgSrcPath + "women_category.png"),
  menCategory: require(imgSrcPath + "men_category.png"),
  kidsCategory: require(imgSrcPath + "kids_category.png"),
  accessoriesCategory: require(imgSrcPath + "accessories_category.png"),
  ic_background_ptwentyseven: require(imgSrcPath + "ic_background_ptwentyseven.png"),
  ic_image_wtfifteen: require(imgSrcPath + "ic_image_wtfifteen.png"),
  ic_img02_wtthree: require(imgSrcPath + "ic_img02_wtthree.png"),
  layout_image_wtsixteen: require(imgSrcPath + "layout_image_wtsixteen.png"),
  ic_img01_wtthree: require(imgSrcPath + "ic_img01_wtthree.png"),
  filter: require(imgSrcPath + "ic_filter.png"),

  //Music Images
  musicBg: require(imgSrcPath + "musicBg.png"),
  musicProfile: require(imgSrcPath + "ic_music_profile.png"),
  musicImgOne: require(imgSrcPath + "ic_music_list_one.png"),
  musicImgTwo: require(imgSrcPath + "ic_music_list_two.png"),
  musicImgThree: require(imgSrcPath + "ic_music_list_three.png"),
  albumBg: require(imgSrcPath + "albumBg.png"),
  galleryImgOne: require(imgSrcPath + "galleryImgOne.png"),
  galleryImgTwo: require(imgSrcPath + "galleryImgTwo.png"),
  galleryImgThree: require(imgSrcPath + "albumBg.png"),
  galleryImgFour: require(imgSrcPath + "galleryImgFour.png"),
  playerProfile: require(imgSrcPath + "playerProfile.png"),
  playerDetail: require(imgSrcPath + "playerDetails.png"),

  //blog Images
  img_user: require(imgSrcPath + "img_user.png"),
  categoryListBg: require(imgSrcPath + "category_list_bg.png"),
  catOne: require(imgSrcPath + "catOne.png"),
  catTwo: require(imgSrcPath + "catTwo.png"),
  catThree: require(imgSrcPath + "catThree.png"),
  catFour: require(imgSrcPath + "catFour.png"),
  catFive: require(imgSrcPath + "catFive.png"),
  catSix: require(imgSrcPath + "catSix.png"),

  trendingOne: require(imgSrcPath + "trendingOne.png"),
  trendingTwo: require(imgSrcPath + "trendingTwo.png"),
  trendingThree: require(imgSrcPath + "trendingThree.png"),

  blogOne: require("../Images/blogOne.png"),
  blogTwo: require("../Images/blogTwo.png"),
  blogThree: require("../Images/blogThree.png"),
  blogFour: require("../Images/blogFour.png"),
  blogFive: require("../Images/blogFive.png"),
  blogSix: require("../Images/blogSix.png"),

  paginationLeftArrow: require("../Images/paginationLeftIcon.png"),
  paginationRightArrow: require("../Images/paginationRightArrow.png"),
  readMoreArrow: require("../Images/readMoreArrow.png"),
  readMoreLeftArrow: require("../Images/readMoreLeftArrow.png"),

  profile_one: require("../Images/profile_one.png"),
  backkground: require("../Images/backkground.png"),
  pro_2: require("../Images/pro_2.png"),

  heart_selected: require("../Images/blog_selected.png"),
  heart_unselected: require("../Images/blog_unselected.png"),
  No_image_found: require("../Images/No_image.png"),
  back_blogdetail: require("../Images/back_blogdetail.png"),
  blogDrawerBg: require("../Images/blogDrawerBg.png"),
  categoryBgg: require("../Images/categoryBgg.png"),

  //Bubbdy Images
  cardBgSocialTwentyone: require("../Images/cardSocialTewntyOneBg.png"),
  bannerHome: require("../Images/bannerHome.png"),
  letter: require("../Images/ic_letter.png"),
  loveArrow: require("../Images/ic_love_arrow.png"),
  loveDevil: require("../Images/ic_love_devil.png"),
  loveLock: require("../Images/ic_love_lock.png"),
  mobile: require("../Images/ic_mobile.png"),
  teddy: require("../Images/ic_teddy.png"),
  gift: require("../Images/ic_gift.png"),
  heartBalloon: require("../Images/ic_heart_balloon.png"),
  puppy: require("../Images/ic_puppy.png"),
  rings: require("../Images/ic_rings.png"),
  rose: require("../Images/ic_rose.png"),
  profileBgImg: require("../Images/ic_profile_bg_img.png"),
  bag: require("../Images/ic_bag.png"),

  //Traveling Images
  destination_two: require("../Images/destination_two.jpeg"),
  destinationimg: require("../Images/destinationimg.jpeg"),
  download: require("../Images/download.jpeg"),
  maxcio_img: require("../Images/maxcio_img.jpeg"),
  maxico_two: require("../Images/maxico_two.jpeg"),
  maxico: require("../Images/maxico.jpeg"),
  wonderfulMaxico: require("../Images/wonderfulMaxico.jpeg"),
  maxcio_one: require("../Images/maxcio_one.jpeg"),
  paris_one: require("../Images/paris_one.jpeg"),
  bgimg: require("../Images/bgimg.jpeg"),
  destinationfound_one: require("../Images/destinationfound_one.jpeg"),
  destinationfound_two: require("../Images/destinationfound_two.jpeg"),
  detinationfound_three: require("../Images/detinationfound_three.jpeg"),
  destinationfound_four: require("../Images/destinationfound_four.jpeg"),
  Destinationstype: require("../Images/Destinationstype.png"),
  transporation: require("../Images/transporation.png"),
  cancun_img: require("../Images/ic_cancun_img.jpg"),
  playa_img: require("../Images/ic_playa_img.jpg"),
  guadalajara_img: require("../Images/ic_guadalajara_img.jpg"),
  lost_inca: require("../Images/ic_lost_inca.jpg"),
  love_paris: require("../Images/ic_love_paris.jpg"),
  triangle: require("../Images/ic_triangle.png"),
  nature: require("../Images/ic_nature.png"),
  traveling_profile: require("../Images/ic_traveling_profile.jpg"),
  lost_el: require("../Images/ic_lost_el.jpg"),
  mexico: require("../Images/ic_mexico.jpeg"),
  egypt: require("../Images/ic_egypt.jpg"),
  puerto: require("../Images/ic_puerto.jpg"),

  //Food Images
  menu: require("../Images/menu.png"),
  Food_one: require("../Images/Food_one.png"),
  Food_three: require("../Images/Food_three.png"),
  food_login_bg: require("../Images/ic_food_login_bg.png"),
  food_logo: require("../Images/ic_food_logo.png"),
  */
  Food_two: require("../Images/Food_two.png"),
    /*
  Food_four: require("../Images/Food_four.png"),
  seletedstar: require("../Images/seletedstar.png"),
  Photos_four: require("../Images/Photos_four.png"),
  */
  Photos_one: require("../Images/Photos_one.png"),
  /*
  Photos_three: require("../Images/Photos_three.png"),
  Photos_two: require("../Images/Photos_two.png"),
  MapView: require("../Images/MapView.png"),
  Reviews_one: require("../Images/Reviews_one.png"),
  reviews_two: require("../Images/reviews_two.png"),
  Welcome_mainBg: require("../Images/Welcome_mainBg.png"),
  ProfileImg: require("../Images/ProfileImg.png"),
  ProfileBG: require("../Images/ProfileBG.png"),
  ProfileUserImg: require("../Images/ProfileUserImg.png"),
  */
  delivery_boy: require("../Images/ic_delivery_boy.png"),
    /*
  seafood: require("../Images/ic_seafood.jpg"),
  fajitas: require("../Images/ic_fajitas.jpeg"),
  visa_food: require("../Images/ic_visa_food1.png"),
  paypal_food: require("../Images/ic_paypal_food2.png"),
  master_food: require("../Images/ic_master_card_food1.png"),
  Food_Img_one: require("../Images/BBButchers-CarpetBaggerAppetizer.jpg"),
  Food_Img_two: require("../Images/BBButchers-Cheesecake.jpg"),
  Food_Img_three: require("../Images/BBButchers-ChocolateCake-2.jpg"),
  Food_Img_four: require("../Images/BBButchers-Cocktail.jpg"),
  Food_Img_five: require("../Images/BBButchers-CremeBrulee.jpg"),
  Food_Img_six: require("../Images/BBButchers-FiletCarpetBagger.jpg"),
  Food_Img_seven: require("../Images/BBButchers-LambBurger.jpg"),
  Food_Img_eight: require("../Images/BBButchers-Oysters.jpg"),
  Food_Img_Nine: require("../Images/BBButchers-QuailDish.jpg"),
  Food_Img_ten: require("../Images/BBButchers-ShrimpCocktail.jpg"),
  Food_Img_ic_one: require("../Images/BBButchers-SteakSalad.jpg"),
  Food_Img_ic_two: require("../Images/BBButchers-StuffedTrout.jpg"),
  Food_Img_ic_three: require("../Images/BBButchers-TBone.jpg"),
  Food_Img_ic_four: require("../Images/bg-homepage-burger.jpg"),
  Food_Img_ic_five: require("../Images/bg-homepage-cafeannie.jpg"),
  Food_Img_ic_six: require("../Images/bg-homepage-egsalad.jpg"),
  Food_Img_ic_seven: require("../Images/bg-homepage-fc.jpg"),
  Food_Img_ic_eight: require("../Images/bg-homepage-kai.jpg"),
  Food_Img_ic_nine: require("../Images/bg-homepage-perrys.jpg"),
  Food_Img_ic_ten: require("../Images/bg-homepage-tejas.jpg"),
  Food_Img_Ic_one: require("../Images/pancakes_pastries_sauce.jpg"),
  Food_Img_Ic_two: require("../Images/cake_plate_cream.jpg"),
  Food_Img_Ic_three: require("../Images/cake_dessert_syrup_baking.jpg"),
  Food_Img_Ic_foue: require("../Images/meat_tomatoes_arugula_lettuce.jpg"),
  Food_Img_Ic_five: require("../Images/strawberry_sauce_pie_segments.jpg"),
  Food_Img_Ic_six: require("../Images/pizza_delicious_pastries_butter.jpg"),
  Food_Img_Ic_seven: require("../Images/salad_seafood_vegetables.jpg"),

  //Vehicle Images
  vehicleLocation: require("../Images/ic_vehicle_location_pin.png"),
  vehicleFuel: require("../Images/ic_vehicle_fuel.png"),
  CarBg: require("../Images/CarBg.png"),
  vehicleFuel: require("../Images/fuel.png"),
  AutoText: require("../Images/AutoText.png"),
  NumberText: require("../Images/NumberText.png"),
  fuleIcon: require("../Images/fuleIcon.png"),
  LocationIcon: require("../Images/LocationIcon.png"),
  MapMarker: require("../Images/MapMarker.png"),
  fuel: require("../Images/fuel.png"),
  AirConditionr: require("../Images/AirConditionr.png"),
  battery: require("../Images/battery.png"),
  IssueNotification: require("../Images/IssueNotification.png"),
  status: require("../Images/status.png"),
  SmartKey: require("../Images/SmartKey.png"),
  Lights: require("../Images/Lights.png"),
  MenuIcon: require("../Images/MenuIcon.png"),
  avg: require("../Images/avg.png"),
  Distance: require("../Images/Distance.png"),
  Duration: require("../Images/Duration.png"),
  speed: require("../Images/speed.png"),
  temp: require("../Images/temp.png"),
  Fan: require("../Images/Fan.png"),
  Dry: require("../Images/Dry.png"),
  coolblack: require("../Images/coolblack.png"),
  coolcolor: require("../Images/coolcolor.png"),
  Dryblack: require("../Images/Dryblack.png"),
  Drycolor: require("../Images/Drycolor.png"),
  Heatblack: require("../Images/Heatblack.png"),
  Heatcolor: require("../Images/Heatcolor.png"),

  //Hotel Images
  teli: require("../Images/teli.png"),
  OrderSuccesfullLogo: require("../Images/OrderSuccesfullLogo.png"),
  hotel_one: require("../Images/hotel_oneadd.jpeg"),
  hotel_two: require("../Images/hotel_two.jpeg"),
  hotel_eight: require("../Images/hotel_eight.jpeg"),
  hotel_nine: require("../Images/hotel_nine.jpeg"),
  hotel_ten: require("../Images/hotel_ten.jpeg"),
  hotel_three: require("../Images/hotel_three.jpeg"),
  hotel_four: require("../Images/hotel_four.jpeg"),
  hotel_five: require("../Images/hotel_five.jpeg"),
  hotel_six: require("../Images/hotel_six.jpeg"),
  hotel_ic_three: require("../Images/hotel_ic_three.jpeg"),
  hotel_ic_four: require("../Images/hotel_ic_four.jpeg"),
  BedroomIcon: require("../Images/BedroomIcon.png"),
  beliconheader: require("../Images/beliconheader.png"),
  air: require("../Images/air.png"),
  clock: require("../Images/clock.png"),
  RoomService: require("../Images/RoomService.png"),
  swimming: require("../Images/swimming.png"),
  wifi: require("../Images/wifi.png"),
  GoogleWalletAR: require("../Images/GoogleWalletAR.png"),
  PaypalAR: require("../Images/PaypalAR.png"),
  kempinski_hotel: require("../Images/kempinski_hotel.jpg"),
  teliscope: require("../Images/teliscope.png"),

  //Crypto Porfolio Images
  cryptoappicon: require("../Images/cryptoappicon.png"),
  cryptoAdd: require("../Images/ic_crypto_add.png"),
  bitcoin: require("../Images/ic_bitcoin.png"),
  ripple: require("../Images/ic_ripple.png"),
  tron: require("../Images/ic_tron.png"),
  eos: require("../Images/ic_eos.png"),
  cardano: require("../Images/ic_cardano.png"),
  chart: require("../Images/ic_chart.png"),
  ethereum: require("../Images/ic_ethereum.png"),
  litecoin: require("../Images/ic_litecoin.png"),
  ic_mailicon: require("../Images/ic_mailicon.png"),
  ethereumGreen: require("../Images/ic_ethereum_green.png"),
  tether: require("../Images/ic_tether.png"),
  deleteImg: require("../Images/deleteImg.png"),
  globalAvg: require("../Images/globalAvg.png"),
  globalAvgArrow: require("../Images/globalAvgArrow.png"),

  //Food Recipe Images
  overViewFoodBg: require("../Images/ic_overview_food_bg.jpeg"),
  foodPasta: require("../Images/ic_pasta.jpg"),
  Trendingrecipeheader: require("../Images/Trendingrecipeheader.jpg"),
  pizzafoodrecipe: require("../Images/pizzafoodrecipe.jpg"),
  pastarecipe: require("../Images/pastarecipe.jpg"),
  Chinessroll: require("../Images/Chinessroll.jpg"),
  Vegburger: require("../Images/Vegburger.jpeg"),
  frankierecipe: require("../Images/frankierecipe.jpg"),
  PaneerBiryaniRecipe: require("../Images/PaneerBiryaniRecipe.jpg"),
  tacostrecipe: require("../Images/tacostrecipe.jpg"),
  chefOne: require("../Images/ic_chef_one.jpeg"),
  chefTwo: require("../Images/ic_chef_two.jpeg"),
  chefThree: require("../Images/ic_chef_three.jpeg"),
  chefFour: require("../Images/ic_chef_four.jpeg"),
  FoodFavorite: require("../Images/FoodFavorite.png"),
  FoodRecipes_one: require("../Images/FoodRecipes_one.jpeg"),
  FoodRecipes_five: require("../Images/FoodRecipes_five.jpeg"),
  FoodRecipes_seaven: require("../Images/FoodRecipes_seaven.jpeg"),
  FoodRecipes_eight: require("../Images/FoodRecipes_eight.jpeg"),
  FoodRecipes_nine: require("../Images/FoodRecipes_nine.jpeg"),
  FoodRecipes_ten: require("../Images/FoodRecipes_ten.jpeg"),
  Dessertimg: require("../Images/Dessertimg.jpeg"),
  sidedishfoodrecipe: require("../Images/sidedishfoodrecipe.jpeg"),
  FoodRecipes_seaven: require("../Images/FoodRecipes_seaven.jpeg"),
  cakerecipeimg: require("../Images/cakerecipeimg.jpeg"),
  dishreceipimg: require("../Images/dishreceipimg.jpg"),
  Saladrecipeimg: require("../Images/Saladrecipeimg.jpeg"),
  ic_food_one: require("../Images/ic_food_one.jpg"),
  ic_food_two: require("../Images/ic_food_two.jpg"),
  ic_food_three: require("../Images/ic_food_three.jpg"),
  ic_food_four: require("../Images/ic_food_four.jpg"),
  ic_food_five: require("../Images/ic_food_five.jpg"),
  ic_food_six: require("../Images/ic_food_six.jpg"),

  //News Media Images
  welcomelogo: require("../Images/welcomelogo.png"),
  playon: require("../Images/playon.png"),
  Reload_one: require("../Images/Reload_one.png"),
  reload_two: require("../Images/reload_two.png"),
  Retenger: require("../Images/Retenger.png"),
  News_one: require("../Images/News_one.jpg"),
  Business: require("../Images/Business.jpg"),
  CultureReligion: require("../Images/CultureReligion.jpg"),
  Entertainment: require("../Images/Entertainment.jpg"),
  Lifestyle: require("../Images/Lifestyle.jpg"),
  Politics: require("../Images/Politics.jpg"),
  Regional: require("../Images/Regional.jpg"),
  Social: require("../Images/Social.jpg"),
  Sports: require("../Images/Sports.jpg"),
  technology: require("../Images/technology.jpg"),
  BeautifulWordpress: require("../Images/BeautifulWordpress.jpg"),
  GlobalWarming: require("../Images/GlobalWarming.jpg"),
  Spotlight: require("../Images/Spotlight.jpg"),
  USPresident: require("../Images/USPresident.jpg"),
  Technology_one: require("../Images/Technology_one.jpg"),
  Techno_two: require("../Images/Techno_two.jpg"),
  Techno_three: require("../Images/Techno_three.jpg"),
  Techo_four: require("../Images/Techo_four.jpg"),
  NwesDetaisAIChampions: require("../Images/NwesDetaisAIChampions.jpg"),
  Explore_one: require("../Images/Explore_one.jpg"),
  RecentUpdate_one: require("../Images/RecentUpdate_one.jpg"),
  RecentUpdate_two: require("../Images/RecentUpdate_two.jpg"),
  Instagram_one: require("../Images/Instagram_one.jpg"),
  Instagram_two: require("../Images/Instagram_two.jpg"),
  Tumblr_one: require("../Images/Tumblr_one.jpg"),
  Tumblr_two: require("../Images/Tumblr_two.jpg"),
  Tumblr_three: require("../Images/Tumblr_three.jpg"),
  Thumblr_four: require("../Images/Thumblr_four.jpg"),
  Featured_News_one: require("../Images/Featured_News_one.jpg"),
  Featured_News_two: require("../Images/Featured_News_two.jpg"),
  RecentPlayed_one: require("../Images/RecentPlayed_one.jpg"),
  RecentPlayed_two: require("../Images/RecentPlayed_two.jpg"),
  RadioLive: require("../Images/RadioLive.jpg")
*/
};

export default images;
